import Navbar from "@/components/Navbar"
import { NextIntlClientProvider } from "next-intl"
import { useMessages } from "next-intl"
import { Rubik } from "next/font/google";
import "../globals.css";
import Landing from "@/components/Landing";

const rubik = Rubik({
    variable: "--font-rubik-sans",
    subsets: ['latin']
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function LocaleLayout(props) {
    const children = props.children
    // const locale = props.params.locale
    const locale='en'
    const messages = useMessages()

    return (
        <html lang={locale}>
            <body className={`${rubik.variable} ${locale === 'ar' ? 'font-arabic rtl' : 'font-english ltr'} min-h-screen`}>
                <NextIntlClientProvider locale={locale} messages={messages}>
                    <main className="flex min-h-screen flex-col">
                        <Navbar />
                        <Landing />
                        {children}
                    </main>
                </NextIntlClientProvider>
            </body>
        </html>
    )
}